### Create Group
POST http://localhost:1323/groups
Content-Type: application/json

{
    "groupId": "a01",
    "name": "Sensor Group A",
    "description": "Group for temperature sensors"
}

### Update Group
PUT http://localhost:1323/groups/a04
Content-Type: application/json

{
    "name": "Sensor Group B",
    "description": "Group for temperature sensors in the bed room"
}

### Get Group by ID
GET http://localhost:1323/groups/a04

### List all Groups
GET http://localhost:1323/groups


### Get data for a group
GET http://localhost:1323/groups/a04/sensors